name: fluid_nav_bar
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^0.60.1
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  flutter_hooks: ^0.12.0
  uuid: ^2.1.0
  hooks_riverpod: ^0.5.1
  stop_watch_timer: ^0.4.0
  intl: ^0.16.1
  quiver: ^2.1.3
  shared:
    path: ../_shared

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 200
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 800

  assets:
    - fonts/google_fonts/
    - assets/images/
    - assets/images/birds/
    - assets/images/flokk-logo.svg
    - assets/images/avatars/
    - assets/icons/

