name: fluid_nav_bar
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^0.60.1
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  flutter_hooks: ^0.12.0
  uuid: ^2.1.0
  hooks_riverpod: ^0.5.1
  stop_watch_timer: ^0.4.0
  intl: ^0.16.1
  quiver: ^2.1.3
  goswimclub_assets:
    path: packages/goswimclub_assets
  shared:
    path: ../_shared

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: BalooTamma
      fonts:
        - asset: packages/goswimclub_assets/fonts/BalooTamma-Regular.ttf
          weight: 400
        - asset: packages/goswimclub_assets/fonts/BalooTamma-Medium.ttf
          weight: 500
        - asset: packages/goswimclub_assets/fonts/BalooTamma-SemiBold.ttf
          weight: 600
        - asset: packages/goswimclub_assets/fonts/BalooTamma-Bold.ttf
          weight: 700
        - asset: packages/goswimclub_assets/fonts/BalooTamma-ExtraBold.ttf
          weight: 800

    - family: Lato
      fonts:
        - asset: packages/goswimclub_assets/fonts/Lato-Thin.ttf
          weight: 200
        - asset: packages/goswimclub_assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: packages/goswimclub_assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: packages/goswimclub_assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: packages/goswimclub_assets/fonts/Lato-Black.ttf
          weight: 800

  assets:
    - assets/images/
    - assets/images/birds/
    - assets/images/flokk-logo.svg
    - assets/images/avatars/
    - assets/icons/

